# Generated by Django 3.1.1 on 2020-11-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201109_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='Phone',
        ),
    ]
