# Generated by Django 3.1.3 on 2020-11-09 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201109_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Phone',
            new_name='phone',
        ),
    ]
